export type Severity = 'low' | 'medium' | 'high' | 'critical';
export type ThreatStatus = 'clean' | 'suspicious' | 'malicious' | 'blocked' | 'quarantined';
export interface Device { id:string; hostname:string; type:'laptop'|'phone'|'iot'|'server'|'router'|'firewall'|'switch'; os:string; ip:string; mac:string; department:string; location:string; subscriberId:string; riskScore:number; status:'online'|'offline'|'quarantined'|'compromised'; health:'healthy'|'warning'|'critical'; applications:string[]; lastSeen:string; connections:string[] }
export interface Packet { id:string; sourceIp:string; destinationIp:string; sourceDevice:string; destinationDevice:string; protocol:'TCP'|'UDP'|'ICMP'|'DNS'|'HTTP'|'HTTPS'|'SSH'|'SMTP'|'FTP'; port:number; payloadSize:number; timestamp:string; subscriberId:string; sliceId:string; riskScore:number; threatStatus:ThreatStatus; threatId?:string; country:string; mitreTechnique?:string; suricataRule?:string; zeekUid?:string; virusTotalStatus?:'clean'|'suspicious'|'malicious'|'unknown'; aiExplanation?:string; recommendation?:string; policyAction:'allow'|'monitor'|'investigate'|'block'|'quarantine' }
export interface Subscriber { imsi:string; name:string; department:string; role:string; email:string; devices:string[]; riskScore:number; riskLevel:'low'|'medium'|'high'|'critical'; status:'active'|'suspended'|'under_investigation'; behaviorScore:number; alerts:string[]; incidents:string[] }
export interface Threat { id:string; name:string; type:string; severity:Severity; status:'active'|'investigating'|'contained'|'resolved'; source:string; destination:string; subscriberId:string; deviceId:string; mitreTechnique:string; mitrePhase:string; detectionTime:string; aiConfidence:number; relatedPackets:string[]; investigationId?:string; description:string; recommendation:string }
export interface Investigation { id:string; title:string; status:'open'|'active'|'closed'|'escalated'; severity:Severity; assignee:string; threatIds:string[]; subscriberIds:string[]; deviceIds:string[]; packetIds:string[]; timeline:Array<{id:string;timestamp:string;event:string;type:'detection'|'analysis'|'escalation'|'response'|'resolution';details:string}>; evidence:Array<{id:string;type:'packet'|'log'|'screenshot'|'artifact';description:string;timestamp:string}>; mitreMapping:Array<{technique:string;tactic:string;description:string}>; aiSummary:string; recommendation:string; createdAt:string; updatedAt:string; attackProgress:number; relatedIOCs:Array<{type:'ip'|'domain'|'hash'|'url';value:string;source:string}> }
export interface Policy { id:string; name:string; description:string; type:'detection'|'prevention'|'response'|'compliance'; priority:Severity; status:'active'|'disabled'|'testing'; conditions:Array<{field:string;operator:string;value:string}>; actions:Array<{type:'allow'|'monitor'|'alert'|'investigate'|'block'|'quarantine';description:string}>; triggeredCount:number; lastTriggered?:string; createdAt:string }
export interface ApiKey { id:string; name:string; key:string; environment:'production'|'staging'|'development'; permissions:string[]; status:'active'|'disabled'|'expired'|'revoked'; createdAt:string; lastUsed?:string; expiresAt:string; owner:string; description:string }
export interface Employee { id:string; name:string; email:string; role:'admin'|'analyst'|'operator'|'viewer'; department:string; status:'active'|'suspended'|'inactive'; lastLogin:string; permissions:string[] }
export interface AppNotification { id:string; severity:'info'|'warning'|'critical'|'success'; title:string; message:string; module:string; timestamp:string; read:boolean; actionUrl?:string }
export interface AuditLog { id:string; timestamp:string; administrator:string; action:string; ipAddress:string; module:string; status:'success'|'failed'; details:string }
